### ISSUE TITLE
groups of groups

### ISSUE THREAD

**Issue by MihaiPop** [thegenemyers/DAS-SPEC#2]
Can we allow groups to be part of groups?  Some hierarchical graph decompositions make sense for complex variant structures.  I know it will make parsing more of a pain, though.

**Comment by thegenemyers** [comment]
Its possible.  Everything can have an id so the rule in understanding to 
what an id refers
to in a group specification would be:

if id is in set of segment ids then
    id refers to that segment
else if id is in set of edge ids then
    id refers to that edge
else if id is in set of group ids then
    id refers to that group
else
    error, undefined id

Since id's are any printable string, one can then allocate ids in such a 
way that the above will
always work.  As a simple example, one could use S# for segment, E# for 
edges, and G# for
groups.

```
-- Gene
```
